### ISSUE TITLE
スマホ表示に関するバグ

### ISSUE THREAD

**Issue by chizuchizu** [Chizuchizu/chizu_blog_hugo#12]
https://twitter.com/tattitaipingu/status/1265519943883333633

Twitter埋め込みをすると見切れてしまう。多分設定でなんとかなるので、暇なときにやります。

**Comment by yayoimizuha** [comment]
大丈夫だったぽい？Closeしちゃって

**Comment by chizuchizu** [comment]
良くなったようなので閉じます
