### ISSUE TITLE
プライバシーポリシー

### ISSUE THREAD

**Issue by chizuchizu** [Chizuchizu/chizu_blog_hugo#16]
to be continued(明日)

**Comment by yayoimizuha** [comment]
https://yayoimizuha.web.app/privacy-policy/
参考にしてくれ

**Comment by yayoimizuha** [comment]
https://github.com/Chizuchizu/chizu_blog_hugo/pull/17/commits/d33b94d9fdc8cb3bfd874e19e80df7cf57131c72

**Comment by yayoimizuha** [comment]
あとでこいつを実装
https://github.com/burnworks/ga-cookie-opt-in-js
自分のサイトに設置したことあるのでたぶんいける

**Comment by chizuchizu** [comment]
ありがとうございます。

**Comment by yayoimizuha** [comment]
done
