### ISSUE TITLE
モバイルページの表示がなんか変

### ISSUE THREAD

**Issue by yayoimizuha** [Chizuchizu/chizu_blog_hugo#24]
@opera7133 何かわかる？

**Comment by opera7133** [comment]
iPhone8で試したけど特に問題はなかった
あるといえばダークモード時にDisqusのテキストが黒で見づらいのと、なぜかPaginationのテキストがdisplay noneになっていること

**Comment by yayoimizuha** [comment]
直しといてくれるか？

**Comment by yayoimizuha** [comment]
できてますね
