### ISSUE TITLE
アイキャッチ画像の実装

### ISSUE THREAD

**Issue by chizuchizu** [Chizuchizu/chizu_blog_hugo#3]
やる予定です。

**Comment by yayoimizuha** [comment]
OGPってこと？

**Comment by chizuchizu** [comment]
それだ！

**Comment by chizuchizu** [comment]
ただ、普通にやるとこんぐらい大きくなっちゃうのでどうにかさせたい

![Screenshot from 2020-05-26 17-12-54](https://user-images.githubusercontent.com/44621609/82898407-3e743200-9f94-11ea-9185-5907ddc2a758.png)

**Comment by yayoimizuha** [comment]
これはどうやって挿入した？

**Comment by chizuchizu** [comment]
単純に記事の.mdの上に  
`img=["icon.png"]`  
を追加しただけ

**Comment by yayoimizuha** [comment]
枠組み自体はあるっぽいから多少配列変えてCSSで殴るだけか

**Comment by chizuchizu** [comment]
大天才 よくわからないので調べてみます

**Comment by yayoimizuha** [comment]
` img=["icon.png"]`追加しても何も起こらないが...？

**Comment by chizuchizu** [comment]
相対パス省略しました

もしやるなら `"img/main/icon.png"` だと思います

**Comment by yayoimizuha** [comment]
#8

**Comment by yayoimizuha** [comment]
https://github.com/Chizuchizu/chizu_blog_hugo/pull/8/commits/fcbf9061289ff1053cf92477b7437d3a843da248
https://github.com/Chizuchizu/chizu_blog_hugo/pull/8/commits/1f5c0b9e803813e6fb9fb8f596906f2b3155c87a
対応完了しました。Mergeして閉じといてください

**Comment by chizuchizu** [comment]
ありがとうございました！！！
