### ISSUE TITLE
dark theme計画

### ISSUE THREAD

**Issue by chizuchizu** [Chizuchizu/chizu_blog_hugo#5]
こんなのがあった。いつかやってみる。

https://discourse.gohugo.io/t/how-to-have-a-dark-mode-for-a-hugo-site/19848

**Comment by yayoimizuha** [comment]
まだ切り替えスイッチ未実装なのでCloseしないで😢

**Comment by chizuchizu** [comment]
再開！（プルリクと連携させたらプルリクmerge時に勝手にcloseしてしまった）

**Comment by chizuchizu** [comment]
ありがとうございましｔ！！！！！！！！１
