### ISSUE TITLE
自動デプロイ

### ISSUE THREAD

**Issue by yayoimizuha** [Chizuchizu/chizu_blog_hugo#7]
コミットされたら自動的にGitHub  ActionsでFTPにアップロードするようにすると頭いいかも
[Github ActionsでHugo使う方法](https://raahii.github.io/posts/automating-hugo-builds-with-github-actions/)
[FTPでアップロードする方法](https://qiita.com/chieeeeno/items/6be835c74d6d7f597c6a)

**Comment by chizuchizu** [comment]
ワークフローとしては

1. ファイルをgithubにpush
2. 自動でビルド
3. publicフォルダ内のファイルをxserverにアップロード

ということでいいんですよね？ ちょっと怖いですが、xserver内のpublic_html内は最悪全部ふっ飛ばしても何とかなるのでやってみます。(時間があるときに)

**Comment by yayoimizuha** [comment]
というか、毎回吹っ飛ばすの前提では(FTPって差分アップロードとかできるのか)

**Comment by chizuchizu** [comment]
サーバーにぶん投げて上書き？？（できるかわからない）

というと、サーバー内のぶち込むフォルダ内を全部消してからってことか

**Comment by yayoimizuha** [comment]
これとは別？
[HUGOでビルドしたpublic配下のファイルをgitと連動させてXserverへ自動デプロイする](https://note.gorogolog.xyz/posts/hugo-git-deploy-xserver/)

**Comment by chizuchizu** [comment]
やってることが高度でいまいち掴めなかったけどビルドはローカルってことなんかな

よくわからない……

**Comment by yayoimizuha** [comment]
リモートだよ

**Comment by chizuchizu** [comment]
もう少し読み込んでみます……

GitHub Actionsでアップロードするのとそのやり方とではどっちのほうが良いんですか？（前者のほうが簡単そう）

**Comment by yayoimizuha** [comment]
私の言った方法でやれば、脳死で記事コミットするだけで自動的にウェブページが公開できるようになる

**Comment by chizuchizu** [comment]
それって最初の方法？  僕もGitHub Actions興味あるのでやりたい（やる）

**Comment by yayoimizuha** [comment]
yes

**Comment by chizuchizu** [comment]
エラー出てた
https://github.com/Chizuchizu/chizu_blog_hugo/blob/master/.github/workflows/main.yml

https://github.com/Chizuchizu/chizu_blog_hugo/actions/runs/116380726

**Comment by yayoimizuha** [comment]
https://github.com/marketplace/actions/fast-ftp-deploy これ使ってみたら？

**Comment by chizuchizu** [comment]
できました @yayoimizuha 本当にありがとう！！！！！！

**Comment by yayoimizuha** [comment]
こいつ、、、動くぞ！！！(感涙)

**Comment by chizuchizu** [comment]
涙が出そうです   先輩……
